### PR TITLE
exclude test for combination of 'length' and 'minLength' facets

### LINKED ISSUE #82: TCK Challenge -- Incorrect requirement around combination of 'length' and 'minLength' facets
### Summary

Two TCK tests are requiring behavior related to the relationship between 'length' and 'minLength' facets on a simple type that go beyond what XML Schema requires. They expect the JAXB implementation to reject compilation of xsds that are valid. Implementors could pass these tests for many years due to bugs in Xerces or Java SE's internal adaption of xerces, but since January 2022 Xerces and the various SE releases have been rolling out fixes for that bug and the tests will not pass using the latest Xerces or SE releases.

### The Challenge

The two tests in question are negative tests that expect the implementation to fail to compile the test xsd. The tests both use an equivalent xsd.

1) xml_schema/msData/datatypes/Facets/Schemas/jaxb/IDREFS_length006_395.html#IDREFS_length006_395 

The xsd is as follows:

https://github.com/jakartaee/jaxb-tck/blob/master/xml_schema/tests/xml_schema/msData/datatypes/Facets/Schemas/IDREFS_length006.xsd

```
<?xml version='1.0'?>
<xsd:schema xmlns:xsd='http://www.w3.org/2001/XMLSchema' >
<!-- Schema to test IDREFS datatype -->
  <xsd:element name='test' type='fooType' />
  <xsd:complexType name='fooType' > 
    <xsd:sequence>
      <xsd:element name='foo' >
        <xsd:complexType>
          <xsd:simpleContent>
            <xsd:extension base="xsd:string">
              <xsd:attribute name='attrTest'>
                <xsd:simpleType> 
                  <xsd:restriction base="xsd:IDREFS">
                            <xsd:length value="5"/>
                            <xsd:minLength value="1"/>
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:attribute>
            </xsd:extension>
          </xsd:simpleContent>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>
```

2) xml_schema/msData/datatypes/Facets/Schemas/jaxb/NMTOKENS_length006_438.html#NMTOKENS_length006_438

The xsd used is :

https://github.com/jakartaee/jaxb-tck/blob/master/xml_schema/tests/xml_schema/msData/datatypes/Facets/Schemas/IDREFS_length006.xsd

The xsd content is the same as the previous one so I won't repost it.

Both are based on and restrict the IDREFs type:

http://www.w3.org/2001/XMLSchema

```
<xs:simpleType name="IDREFS" id="IDREFS">
  <xs:annotation>
    <xs:appinfo>
      <hfp:hasFacet name="length"/>
      <hfp:hasFacet name="minLength"/>
      <hfp:hasFacet name="maxLength"/>
      <hfp:hasFacet name="enumeration"/>
      <hfp:hasFacet name="whiteSpace"/>
      <hfp:hasFacet name="pattern"/>
      <hfp:hasProperty name="ordered" value="false"/>
      <hfp:hasProperty name="bounded" value="false"/>
      <hfp:hasProperty name="cardinality" value="countably infinite"/>
      <hfp:hasProperty name="numeric" value="false"/>
    </xs:appinfo>
    <xs:documentation source="http://www.w3.org/TR/xmlschema-2/#IDREFS"/>
  </xs:annotation>
  <xs:restriction>
    <xs:simpleType>
      <xs:list itemType="xs:IDREF"/>
    </xs:simpleType>
    <xs:minLength value="1" id="IDREFS.minLength"/>
  </xs:restriction>
</xs:simpleType>
```

In effect the test xsds add to the base type restriction that the list minLength is 1 an additional restriction that the list length must be 5. The xsds also repeat the base type's restriction that minLength = 1.

The tests expect compilation to fail. Perhaps this was because at some point the thinking was combining 'length' and 'minLength' was invalid. I don't know.  But the XML Schema 2: Datatypes document lists the requirements around 'length' facets:

https://www.w3.org/TR/xmlschema-2/#rf-facets

```
4.3.1.4 Constraints on length Schema Components

Schema Component Constraint: length and minLength or maxLength

If length is a member of {facets} then

1. It is an error for minLength to be a member of {facets} unless
  1.1 the {value}] of minLength <= the {value} of length and
  1.2 there is type definition from which this one is derived by one or more restriction steps in which minLength has the same {value} and length is not specified.
2 It is an error for maxLength to be a member of {facets} unless
  2.1 the {value} of length <= the {value} of maxLength and
  2.2 there is type definition from which this one is derived by one or more restriction steps in which maxLength has the same {value} and length is not specified.

Schema Component Constraint: length valid restriction

It is an ·error· if length is among the members of {facets} of {base type definition} and {value} is not equal to the {value} of the parent length.
```

Neither of the TCK xsds shown above violate these constraints, so there is no reason they should fail to compile.

### Background Info -- the Xerces/Java SE bug

Until recently JAXB implementations may not have been aware that the test was making an invalid assertion because of a bug in Xerces and Java SE that caused compilation of the test xsds to fail (and thus the negative tests to pass):

https://issues.apache.org/jira/browse/XERCESJ-1729

This was fixed in Xerces 2.12.2, released in January 2022.  Following that OpenJDK began porting the Xerces 2.12.2 fixes into Java SE (for SE 19):

https://bugs.openjdk.org/browse/JDK-8282280

Backports to other SE branches were done; the complete list is shown in JDK-8282280. For the LTS SE streams it was resolved in October 2022 in SE 11.0.17 (https://bugs.openjdk.org/browse/JDK-8290810) and in SE 17.0.5 (https://bugs.openjdk.org/browse/JDK-8290508).

As test environments move to more recent Xerces or Java SE releases I expect they will start to fail these tests.

### PR DESCRIPTION
**Pull request by lukasj**
exclude jdk version dependent tests - fixes #82 

@gurunrao can you review and double-check this, please?

### CODE REVIEW

**Review by scottmarlow — APPROVED** [review]

**Comment by scottmarlow** [comment]
@gurunrao is https://ci.eclipse.org/jakartaee-tck/job/10/job/eftl-jaxb-tck-build-run-100 where we should build the XML Binding TCK with this change once merged?

**Comment by gurunrao** [comment]
@lukasj - I have started CI build https://ci.eclipse.org/jakartaee-tck/job/guru/job/jaxb-tck-guru/job/is82/2/ for verification of exclusion. Post completion of build, we can manually verify if test has run or excluded.

**Comment by gurunrao** [comment]
> @lukasj - I have started CI build https://ci.eclipse.org/jakartaee-tck/job/guru/job/jaxb-tck-guru/job/is82/2/ for verification of exclusion. Post completion of build, we can manually verify if test has run or excluded.



> @gurunrao is https://ci.eclipse.org/jakartaee-tck/job/10/job/eftl-jaxb-tck-build-run-100 where we should build the XML Binding TCK with this change once merged?

We have to run the build https://ci.eclipse.org/jakartaee-tck/job/10/job/eftl-jaxb-tck-build-run-100 post update of Version number, else the Job will over-write existing staged xml-binding tck.

**Comment by gurunrao** [comment]
> @gurunrao is https://ci.eclipse.org/jakartaee-tck/job/10/job/eftl-jaxb-tck-build-run-100 where we should build the XML Binding TCK with this change once merged?

We have to run the build https://ci.eclipse.org/jakartaee-tck/job/10/job/eftl-jaxb-tck-build-run-100 post update of Version number, else the Job will over-write existing staged xml-binding tck.

**Comment by lukasj** [comment]
> post update of Version number, else the Job will over-write existing staged xml-binding tck.

see #84

**Comment by lukasj** [comment]
rebased on master so this gets the correct version number

**Comment by lukasj** [comment]
the test job did not run affected tests, so this is OK

**Pull request merged**
